build:
  maxIssues: 200

style:
  MagicNumber:
    active: false

  MaxLineLength:
    active: true
    maxLineLength: 140

  NewLineAtEndOfFile:
    active: false

  ReturnCount:
    active: false

  UnusedPrivateMember:
    active: false

complexity:
  LongMethod:
    active: true
    threshold: 180

  LongParameterList:
    active: false

  TooManyFunctions:
    active: true
    thresholdInFiles: 30
    thresholdInClasses: 30
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

  CyclomaticComplexMethod:
    active: true
    threshold: 20

exceptions:
  TooGenericExceptionCaught:
    active: false

comments:
  UndocumentedPublicClass:
    active: false

  UndocumentedPublicFunction:
    active: false

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - Composable

  MatchingDeclarationName:
    active: false